### PR TITLE
fix: #52 updated to pagination aware memory delete

### LINKED ISSUE #52: BUG] deleteByConversationId() only deletes first page of events  orphans remaining data
### Description

`AgentCoreShortTermMemoryRepository.deleteByConversationId()` calls `listEvents` once with `maxResults(pageSize)` but never paginates using `nextToken`. If a conversation has more events than `pageSize`, the remaining events are silently orphaned.

**File:** `spring-ai-agentcore-memory/src/main/java/org/springaicommunity/agentcore/memory/shorttem/AgentCoreShortTermMemoryRepository.java`

### Current Code

```java
@Override
public void deleteByConversationId(String conversationId) {
    // ...
    var listEventsRequest = ListEventsRequest.builder()
        .memoryId(memoryId)
        .actorId(actorAndSession.actor())
        .sessionId(actorAndSession.session())
        .includePayloads(false)
        .maxResults(pageSize)       // fetches ONE page only
        .build();

    var events = client.listEvents(listEventsRequest).events();
    events.forEach(event -> client.deleteEvent(...));
    // ^^^ never checks nextToken — remaining pages are silently skipped
}
```

Note: `fetchAllEvents()` in the **same class** correctly paginates with a `do/while` loop and `nextToken`. The delete method is simply missing the same pattern.

### Impact in Production

- Long-running conversations accumulate events beyond `pageSize`
- Calling delete only removes the first page (e.g., 50 of 150 events)
- Remaining 100 events persist in AgentCore storage indefinitely
- Logs say "Successfully deleted 50 events" — no indication of data left behind
- Orphaned events consume storage and incur cost with no way to detect them

### Steps to Reproduce

1. Create a conversation with more events than the default `pageSize` (e.g., send 150+ messages in a single conversation).

2. Call `deleteByConversationId()`:
   ```java
   repository.deleteByConversationId("user123/session1");
   ```

3. Check the logs — it will say something like:
   ```
   Successfully deleted 50 events for conversation: user123/session1
   ```

4. Call `findByConversationId()` for the same conversation — it returns empty because `findByConversationId` uses `fetchAllEvents()` which starts from the newest page (the remaining events are older and were the ones orphaned).

5. However, the orphaned events still exist in AgentCore storage. You can verify by calling the `ListEvents` API directly with pagination — the old events are still there, consuming storage.

**Expected:** All events for the conversation are deleted regardless of count.  
**Actual:** Only the first `pageSize` events are deleted. The rest are silently orphaned.

**Key observation:** `fetchAllEvents()` in the same class correctly paginates:
```java
do {
    // ... fetch page ...
    nextToken = listEventsResponse.nextToken();
} while (nextToken != null);
```
I will submit a PR with the fix.

### PR DESCRIPTION
**Pull request by ashakirin**
Fix #52: Pagination aware memory delete

### CODE REVIEW

**Comment by ashakirin** [comment]
Duplicates https://github.com/spring-ai-community/spring-ai-agentcore/pull/55

File: spring-ai-agentcore-memory/src/main/java/org/springaicommunity/agentcore/memory/shorttem/AgentCoreShortTermMemoryRepository.java [hunk 1]
```diff
@@ -290,30 +263,62 @@ public void deleteByConversationId(String conversationId) {
 
 		try {
 			var actorAndSession = actorAndSession(conversationId);
+			var deleted = new int[1];
```
Comment (maschnetwork) [inline spring-ai-agentcore-memory/src/main/java/org/springaicommunity/agentcore/memory/shorttem/AgentCoreShortTermMemoryRepository.java]: Why is this an array?

Comment (ashakirin) [reply spring-ai-agentcore-memory/src/main/java/org/springaicommunity/agentcore/memory/shorttem/AgentCoreShortTermMemoryRepository.java]: @maschnetwork variable have to be effectively final, because of usage in lambda. AtomicInteger will be more descriptive here
