### PR TITLE
Replace unbounded ConcurrentHashMap with bounded Caffeine cache in RateLimitingFilter

### LINKED ISSUE #51: [BUG] RateLimitingFilter: Unbounded memory leak ConcurrentHashMap never evicts per-client buckets
### Description

`RateLimitingFilter` stores per-client rate limit buckets in a `ConcurrentHashMap` that never evicts entries. Every unique client IP permanently allocates a `Bucket` object that is never removed.

**File:** `spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java`

### Current Code (line 48)

```java
private final ConcurrentHashMap<String, Bucket> buckets = new ConcurrentHashMap<>();
```

There is no `remove()`, no TTL, no max size anywhere in the class. The `getBucket()` method only ever adds:

```java
private Bucket getBucket(String clientId, String path) {
    var key = clientId + ':' + path;
    return buckets.computeIfAbsent(key, k -> createBucket(path));  // only adds, never removes
}
```

### Impact in Production

- Behind a load balancer/CDN, `X-Forwarded-For` carries a different IP per end user
- Each unique IP permanently allocates ~200-500 bytes (Bucket + internal state)
- 100k unique users/day → ~50 MB/day of heap never freed
- Under DDoS/bot scan → millions of entries in hours → `OutOfMemoryError`
- Hard to catch in dev/staging — not enough unique IPs

### Steps to Reproduce

1. Start any Spring Boot app using `spring-ai-agentcore-runtime-starter` with rate limiting enabled:
   ```properties
   agentcore.throttle.invocations-limit=10
   agentcore.throttle.ping-limit=5
   ```

2. Send requests to `/invocations` with different `X-Forwarded-For` headers simulating unique clients:
   ```bash
   for i in $(seq 1 100000); do
     curl -s -X POST http://localhost:8080/invocations \
       -H "Content-Type: application/json" \
       -H "X-Forwarded-For: 10.0.$((i/256)).$((i%256))" \
       -d '{"prompt":"test"}' > /dev/null
   done
   ```

3. Monitor heap usage via JMX, Actuator (`/actuator/metrics/jvm.memory.used`), or VisualVM.

**Expected:** Heap stays flat after initial warmup.  
**Actual:** Heap grows linearly and never reclaims. Each unique IP permanently adds a Bucket to the internal `ConcurrentHashMap`.

### Measured Results (standalone simulation with 500k unique IPs)

```
BUGGY (ConcurrentHashMap, no eviction):
  After 100,000 IPs → buckets: 100,000 | heap:  34 MB
  After 300,000 IPs → buckets: 300,000 | heap:  99 MB
  After 500,000 IPs → buckets: 500,000 | heap: 165 MB  ← never freed

FIXED (Caffeine cache, 100k max + 5min TTL):
  After 100,000 IPs → buckets: 100,000 | heap:  40 MB
  After 300,000 IPs → buckets: 100,000 | heap:  40 MB  ← stays flat
  After 500,000 IPs → buckets: 100,000 | heap:  40 MB
```

I will submit a PR with the fix.

### PR DESCRIPTION
**Pull request by vaquarkhan**
## Summary

`RateLimitingFilter` stores per-client rate limit buckets in a `ConcurrentHashMap` that never evicts entries. Every unique client IP permanently allocates a `Bucket` object (~200-500 bytes) that is never removed. Behind a load balancer, CDN, or under attack, this causes unbounded heap growth until `OutOfMemoryError`.

## Changes

- **`spring-ai-agentcore-runtime-starter/pom.xml`** — Added explicit `caffeine` dependency (already a transitive dependency via Spring Boot)
- **`RateLimitingFilter.java`** — Replaced `ConcurrentHashMap<String, Bucket>` with a bounded `Caffeine Cache<String, Bucket>` (default: 100,000 max entries, 5-minute expiry after last access)

## Before vs After

| Scenario (500k unique IPs) | Buckets in memory | Heap used |
|---|---|---|
| **Before** (ConcurrentHashMap) | 500,000 (never freed) | ~165 MB and growing |
| **After** (Caffeine cache) | 100,000 (capped) | ~40 MB (stays flat) |

## Backward Compatibility

- The existing 2-arg constructor delegates to the new 4-arg constructor with sensible defaults, so no changes needed in `ThrottleConfiguration` or existing tests
- All 80 existing tests pass

## Testing

- `mvn test -pl spring-ai-agentcore-runtime-starter` — 80 tests, 0 failures
- `mvn spring-javaformat:apply` — clean

Fixes #51

### CODE REVIEW

File: spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java [hunk 1]
```diff
@@ -45,13 +46,22 @@ public class RateLimitingFilter implements Filter {
 
 	private static final String UTF_8 = "UTF-8";
 
-	private final ConcurrentHashMap<String, Bucket> buckets = new ConcurrentHashMap<>();
+	private static final long DEFAULT_MAX_BUCKETS = 100_000;
+
+	private static final Duration DEFAULT_BUCKET_EXPIRY = Duration.ofMinutes(5);
```
Comment (maschnetwork) [inline spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java:59]: Why 5 Minutes?

File: spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java [hunk 2]
```diff
@@ -45,13 +46,22 @@ public class RateLimitingFilter implements Filter {
 
 	private static final String UTF_8 = "UTF-8";
 
-	private final ConcurrentHashMap<String, Bucket> buckets = new ConcurrentHashMap<>();
+	private static final long DEFAULT_MAX_BUCKETS = 100_000;
```
Comment (maschnetwork) [inline spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java]: Should we have a lower default here? We assume to have buckets per Agentcore Runtime session.

**Review by maschnetwork — COMMENTED** [review]
Thanks for spotting this. A few minor comments. Can you also please add a test for bounded buckets and eviction?

File: spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java (hunk 1 above)
Comment (vaquarkhan) [reply spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java:59]: Good question , 5 minutes was a conservative default but I can make the reasoning explicit.

The Bandwidth refills the bucket every 1 minute (via .refillIntervally(limit, Duration.ofMinutes(1))). Once a client has been idle for that refill window, its bucket has fully replenished, so evicting and recreating it on the next request has identical semantics to keeping it alive. That means the minimum safe TTL is 1 minute.

I picked 5 minutes (5× the refill window) to cover realistic agent-like traffic patterns  an agent session that pauses briefly, retries after a transient failure, or does a multi-step workflow with natural gaps shouldn't hit a new bucket (and a fresh full capacity) between steps. A 1-minute TTL would allow rate-limit bypass: idle exactly 60 seconds and your quota resets. 5 minutes makes that harder without hurting legitimate usage.

Happy to drop it to 2 or 3 minutes if you'd prefer something tighter. Anything below 1 minute would effectively defeat the rate limit.

File: spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java (hunk 2 above)
Comment (vaquarkhan) [reply spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java]: You're right, if buckets are scoped to AgentCore Runtime sessions rather than raw client IPs, 100k is way oversized. Session counts are typically in the hundreds to low thousands, not hundreds of thousands.

Two options depending on intent:

- Lower the default to 10,000  matches realistic session concurrency with plenty of headroom. Keeps the safety net for IP-keyed scenarios (behind a proxy where X-Forwarded-For carries varied client IPs).

- Lower to 1,000  tight fit for session-scoped use. Better memory footprint but could cause premature eviction if the starter is ever used outside the AgentCore Runtime context (e.g., someone uses this filter for general rate limiting on a public endpoint).

I'd suggest  and updated 10,000 as a middle ground cheap enough in memory (2-5 MB at the Bucket overhead I quoted earlier) while still protecting against pathological IP-keyed bloat. Let me know which you prefer and I'll update.

**Comment by vaquarkhan** [comment]
Added following test case @maschnetwork 
spring-ai-agentcore-runtime-starter/src/test/java/org/springaicommunity/agentcore/throttle/RateLimitingFilterBucketCacheTest.java

shouldNotGrowBeyondMaxBuckets
shouldEvictIdleBucketsAfterExpiry
shouldReuseBucketForSameClient
shouldUseDefaultCacheWithTwoArgConstructor
shouldNotEvictBucketWhileClientKeepsAccessing
shouldRestoreFullCapacityAfterIdleEviction

File: spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java [hunk 3]
```diff
@@ -104,4 +114,9 @@ private Bucket createBucket(String path) {
 		return Bucket.builder().addLimit(bandwidth).build();
 	}
 
+	long bucketCountAfterMaintenance() {
```
Comment (maschnetwork) [inline spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java]: Lets make this clear that this is for testing at least with a comment. Should we rather expose this.buckets and leave the methods for the test setup?

Comment (vaquarkhan) [reply spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java]: should i add comments on class or you want to update documentation ?

Comment (maschnetwork) [reply spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java]: Lets just add a comment here on the class and lets return the buckets package private while leave calling `.cleanUp();` up to the test.

Comment (vaquarkhan) [reply spring-ai-agentcore-runtime-starter/src/main/java/org/springaicommunity/agentcore/throttle/RateLimitingFilter.java]: mplemented your suggestion: added a class Javadoc on RateLimitingFilter, made buckets package-private for tests, and removed bucketCountAfterMaintenance() from the filter so only tests call buckets.cleanUp() before assertions (RateLimitingFilterBucketCacheTest).
